#!/bin/sh
set -e

case "$1" in
    remove|upgrade|deconfigure)
        if [ -d /run/systemd/system ]; then
            deb-systemd-helper stop agent-chiffreur.service >/dev/null 2>&1 || true
            deb-systemd-helper disable agent-chiffreur.service >/dev/null 2>&1 || true
        fi
        ;;
esac

#DEBHELPER#

exit 0
